services:
  web:
    build: .
    volumes:
      - .:/code
  db_migration:
    extends:
      service: web
    command: python manage.py migrate
  runserver:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  tests:
    extends:
      service: web
    command: python -m pytest tests -v
    profiles:
      - test