# Generated by Django 4.2 on 2023-04-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joke', models.TextField()),
            ],
        ),
    ]
